name: Java test build

on:
  pull_request:
    branches: [ development, release/** ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  java_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test
        run: ./gradlew test
      - name: Build
        run: ./gradlew build

  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build  Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          tags: ghcr.io/${{ env.IMAGE_NAME }}:test
